project:
  type: website
  output-dir: docs
  resources:
      - images/
      
website:
  title: "Rachel's First Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research_interests.qmd
        text: Research Interests

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
